### PR TITLE
[#80] Fix: Wrong validating logic for the submit survey responses API

### LINKED ISSUE #80: Fix: Wrong validating logic for the submit survey responses API
## Issue

When the mobile app submits survey responses with a different order of questions compared to the order from the survey detail API, the response will return the error "Questions is invalid"

Screenshot 2023-01-13 at 11 45 57

## Expected

The API should return an empty response with a 201 status code.

Screenshot 2023-01-13 at 11 47 09

## Steps to reproduce

1. Change the order of the question list in the request body.
2. Send a request to the API.

### PR DESCRIPTION
**Pull request by suho**
- Resolves #80

## What happened 👀

For the submitting survey responses API, with our validating logic, we did not allow submitting questions with different orders. I updated the logic to support it.

## Insight 📝

The order of array when using intersection can affect the result. 

`(a & b) == b` is different with `(b & a) == b`

## Proof Of Work 📹

When I added tests with questions that have different orders:

Screenshot 2023-01-13 at 14 26 40

All tests are passed:

Screenshot 2023-01-13 at 14 58 14

### CODE REVIEW

File: app/forms/response_form.rb [hunk 1]
```diff
@@ -26,7 +26,7 @@ def validate_questions
     survey_questions_ids = survey.questions.map(&:id)
     questions_ids = questions.pluck(:id)
 
-    return if (survey_questions_ids & questions_ids) == questions_ids
+    return if (survey_questions_ids & questions_ids).to_set == questions_ids.to_set
```
Comment (hoangmirs) [inline app/forms/response_form.rb:29]: Regarding [this benchmark](https://stackoverflow.com/a/56702586/6339862), should we change to use the `sort!` instead?
```suggestion
    return if (survey_questions_ids & questions_ids).sort! == questions_ids.sort!
```

File: spec/forms/response_form_spec.rb [hunk 2]
```diff
@@ -5,25 +5,50 @@
...
     context 'given valid attributes' do
-      it 'returns true' do
-        questions_ids = [
-          { id: '940d229e4cd87cd1e202' },
-          { id: 'c3a9b8ce5c2356010703' }
-        ]
-        form = described_class.new(survey_id: 'd5de6a8f8f5f1cfe51bc', questions: questions_ids)
-
-        expect(form.save).to eq(true)
+      context 'given a same questions order' do
```
Comment (hoangmirs) [inline spec/forms/response_form_spec.rb:8]: Should it be something like this?
```suggestion
      context 'given a questions_ids param that has the same order as questions in DB' do
```

Comment (hoangmirs) [reply spec/forms/response_form_spec.rb:8]: And same for the below 🙏

File: app/forms/response_form.rb (hunk 1 above)
Comment (suho) [reply app/forms/response_form.rb]: After checking the logic again, I think it's better to update to
`(questions_ids & survey_questions_ids) == questions_ids`

Fixed in https://github.com/nimblehq/nimble-survey-web/pull/82/commits/1985c8b6ffb8e2e2271c59b9ec9622831e945e46

File: spec/forms/response_form_spec.rb (hunk 2 above)
Comment (suho) [reply spec/forms/response_form_spec.rb]: Fixed in https://github.com/nimblehq/nimble-survey-web/pull/82/commits/c9c6b71e2065341d7ce38729584639dfec5ed152

**Review by hoangmirs — APPROVED** [review]

**Review by olivierobert — APPROVED** [review]
Apart from updating the PR description (as Set is not used anymore), the change is good 👍
